#!/bin/sh

# Chwtwork Room ID && TOKEN
CHATWORK_ROOM_ID="${CHATWORK_ROOM_ID}"
CHATWORK_APP_TOKEN="${CHATWORK_APP_TOKEN}"

# Send message to Chatwork
CHATWORK_MESSAGE_HEADER="[info][title]タイトルです。[/title]"
CHATWORK_MESSAGE_MESSAGE="本文"
CHATWORK_MESSAGE_FOOTER="[/info]"
